version: '2'
services:
  proxy:
    build: .
    restart: unless-stopped
    environment:
    - VIRTUAL_HOST=${VIRTUAL_HOST}
    - VIRTUAL_PORT=${VIRTUAL_PORT}
    - ASTERISK_HOST=${ASTERISK_HOST}
    networks:
      - webproxy


networks:
  webproxy:
    external:
      name: webproxy
